spring:
  thymeleaf:
    cache: false
    mode: HTML
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiuxiao.pojo
  configuration:
    map-underscore-to-camel-case: true
